'use strict';

// Все пиксель-спрайты игры: 16x16, '.' — прозрачный пиксель.
// Классы — по референсам игрока; мобы и владыки — уникальный вид для каждого.
const SPRITES = {
  // ================= классы =================
  warrior: {
    pal: { R: '#c03028', r: '#e05848', D: '#701f18', G: '#d8a030', g: '#f4d060', K: '#241a18', O: '#ff9838' },
    grid: [
      '......gGGg.....O',
      '..g..gRRRRg....O',
      '.gRg.GRRRRG.gRgO',
      '.gRggGRRRRGggRgG',
      '..RgGRKKKKRGgR.G',
      '...gGKOOOOKGg..G',
      '....GRKKKKRG...G',
      '..RRGGGGGGGGRR.G',
      '.RRgKKRRRRKKgRRG',
      '.RRgKRGGGGRKgRRG',
      '.RR.KRGDDGRK.RRG',
      '.RR.KRRDDRRK.RRG',
      '..R.KKR..RKK.R.G',
      '...GKK....KKG...',
      '...GGg....gGG...',
      '................',
    ],
  },
  archer: {
    pal: { B: '#4a72c4', b: '#7aa2e8', N: '#2c4a86', S: '#d8dce4', s: '#f6f8fc', G: '#d8a840', g: '#f4d878', K: '#28303c', F: '#e8c498' },
    grid: [
      '......SSSS....g.',
      '..s..SbbbbS..gGg',
      '.ss.SbbbbbbS..G.',
      '.sSSbbSSSSbbSSG.',
      '..SSbFFFFFFbSSG.',
      '...SbFKFFKFbS.G.',
      '....BFFFFFFB..G.',
      '..BBBBBBBBBBB.G.',
      '.BBbBBNBBNBBb.G.',
      '.BBbBNBBBBNBb.G.',
      '.BB.BGGggGGB..G.',
      '..B.BBBNNBBB..G.',
      '....BBB..BBB..G.',
      '...GGB....BGG...',
      '...GGs....sGG...',
      '................',
    ],
  },
  wizard: {
    pal: { P: '#7a4ab0', p: '#a878e0', L: '#d0b8f0', W: '#ece8f4', G: '#d8a840', g: '#f4d878', K: '#241c30', E: '#c060ff' },
    grid: [
      '..g....gg....g..',
      '.gWg..WWWW..gWg.',
      '.gWWWWWWWWWWWg..',
      '..WWWWWWWWWWW.gg',
      '...WPKPPPPKPW.gg',
      '...WPEPPPPEPW.G.',
      '....PKKKKKKP..G.',
      '..WPPPPPPPPPW.G.',
      '.WWpPGPPPPGPpWG.',
      '.WWpPPGGGGPPpWG.',
      '.WW.PGPLLPGP.WG.',
      '..W.PPGLLGPP.WG.',
      '....PPP..PPP..G.',
      '...GPP....PPG...',
      '...GGL....LGG...',
      '................',
    ],
  },

  // ================= лес =================
  wolf: {
    pal: { s: '#9aa2ac', d: '#6a7280', K: '#343a44', E: '#e05848', w: '#e8ecf2' },
    flip: true,
    grid: [
      '................',
      '................',
      '.KK.............',
      'KssK.........KK.',
      'KsEsK.......KsdK',
      '.KssKKKKKKKKsdK.',
      '.KwsssssssssssK.',
      '..KsssdddssssK..',
      '..KssssssssssK..',
      '...KssKsssKssK..',
      '...KsdK.KsdKsdK.',
      '...KKK..KKK.KK..',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  mushroom: {
    pal: { R: '#c84a3c', W: '#f0e6da', F: '#d8c4a0', K: '#3a2c24', E: '#2a1e18' },
    grid: [
      '................',
      '.....KKKKKK.....',
      '...KKRRRRRRKK...',
      '..KRRWRRRRWRRK..',
      '.KRRRRRRWRRRRRK.',
      '.KRRWRRRRRRWRRK.',
      '.KKKKKKKKKKKKKK.',
      '...KFFFFFFFFK...',
      '...KFEFFFFEFK...',
      '...KFFFFFFFFK...',
      '....KFFFFFFK....',
      '....KFFFFFFK....',
      '.....KKKKKK.....',
      '................',
      '................',
      '................',
    ],
  },
  wisp: {
    pal: { G: '#4a9858', g: '#8be89c', E: '#14301c', w: '#d8ffe0' },
    grid: [
      '................',
      '......GGGG......',
      '....GGggggGG....',
      '...GggwggwggG...',
      '..GggEggggEggG..',
      '..GggggggggggG..',
      '..GggggwgggggG..',
      '..GggggggggggG..',
      '...GggGggGggG...',
      '....Gg.Gg.Gg....',
      '....G..G...G....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },

  // ================= земли исполинов =================
  cyclops: {
    pal: { T: '#c8a878', t: '#a8865c', K: '#4a3826', E: '#68c4e8', P: '#1c2830', C: '#7a5838' },
    grid: [
      '.....KKKKK......',
      '....KTTTTTK..CC.',
      '...KTTTTTTTK.CC.',
      '...KTTKEKTTK.CC.',
      '...KTTKPKTTK..C.',
      '....KTTTTTK...C.',
      '..KKTTTTTTTKK.C.',
      '.KTTKTtttTKTTC..',
      '.KTT.KtttK.TTK..',
      '.KTT.KtttK.TC...',
      '..KK.KtttK.C....',
      '.....KtttK......',
      '....KTt.tTK.....',
      '....KT...TK.....',
      '...KKK...KKK....',
      '................',
    ],
  },
  hydra: {
    pal: { g: '#5aa848', d: '#3a7830', K: '#1e3c18', E: '#f0e05a', b: '#c8e87a' },
    grid: [
      '.KK....KK....KK.',
      'KggK..KggK..KggK',
      'KgEK..KgEK..KgEK',
      '.KgK..KggK..KgK.',
      '.KgK...KgK..KgK.',
      '..KgK..KgK.KgK..',
      '...KggKggKggK...',
      '....KggggggK....',
      '...KgbbbbbbgK...',
      '...KgbbbbbbgK...',
      '..KggbbbbbbggK..',
      '..KgggddddgggK..',
      '...KgggggggK....',
      '....KK...KK.....',
      '................',
      '................',
    ],
  },
  phoenix: {
    pal: { o: '#f08030', O: '#c85818', Y: '#f8d048', K: '#4a2410', E: '#2a1408', w: '#ffe8a0' },
    grid: [
      '......KK........',
      '.....KooK.......',
      '.K...KoEK...K...',
      'KoK..KooKw.KoK..',
      'KooK.KooK.KooK..',
      '.KooKKooKKooK...',
      '.KooooooooooK...',
      '..KooYYYYooK....',
      '..KoYYwwYYoK....',
      '...KoYYYYoK.....',
      '....KoYYoK......',
      '.....KYYK.......',
      '....K.YY.K......',
      '.....K.Y..K.....',
      '................',
      '................',
    ],
  },

  // ================= элементальные миньоны =================
  sparkling: {
    pal: { B: '#3a6ac0', b: '#7ab8f0', E: '#0c1830', w: '#e0f0ff' },
    grid: [
      '.......B........',
      '......BBB.......',
      '..B..BbbbB..B...',
      '...BBbwbwbBB....',
      '....BbEbEbB.....',
      '..BBbbbbbbbBB...',
      '.B..BbwwwbB..B..',
      '....BbbbbbB.....',
      '...BBbbbbbBB....',
      '..B..BbbbB..B...',
      '......BBB.......',
      '.......B........',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  triton: {
    pal: { T: '#1e7a72', t: '#4ecdc4', E: '#f0f8ff', g: '#d8a840', w: '#c0f0ec' },
    grid: [
      '......TTTT....g.',
      '....TTttttTT.ggg',
      '...TttttttttT.g.',
      '...TtEttttEtT.g.',
      '...TttttttttT.g.',
      '....TtwwwwtT..g.',
      '..TTttttttttT.g.',
      '.TttTttttttTt.g.',
      '.Ttt.TttttT.t.g.',
      '..TT.TttttT...g.',
      '.....TttttT.....',
      '....TttwwttT....',
      '...Ttt....ttT...',
      '....T......T....',
      '................',
      '................',
    ],
  },
  treant: {
    pal: { B: '#7a5838', b: '#5a3e24', g: '#5aa848', G: '#2e5c22', E: '#c8f060' },
    grid: [
      '....GGGGGGG.....',
      '..GGgggggggGG...',
      '.GgggggggggggG..',
      '.GgggggggggggG..',
      '..GGgggggggGG...',
      '....bBBBBBb.....',
      '....bBEBEBb.....',
      '....bBBBBBb.....',
      '...bBBbBBBBb....',
      '..bBB.bBBB.Bb...',
      '..bB..bBB...b...',
      '.bBB.bBBBb..Bb..',
      '.bB..bBBb...Bb..',
      '.....bBBb.......',
      '....bB..Bb......',
      '................',
    ],
  },
  moonshade: {
    pal: { P: '#4a3468', p: '#6a4c94', E: '#d8b8ff', K: '#241c30' },
    grid: [
      '......KKKK......',
      '.....KPPPPK.....',
      '....KPppppPK....',
      '....KPEppEPK....',
      '....KPppppPK....',
      '...KPPppppPPK...',
      '...KPpKppKpPK...',
      '..KPPp.pp.pPPK..',
      '..KPp..pp..pPK..',
      '..KP...pp...PK..',
      '.KPP...pp...PPK.',
      '.KP....pp....PK.',
      '......KppK......',
      '.......KK.......',
      '................',
      '................',
    ],
  },

  // ================= огненные миньоны =================
  imp: {
    pal: { o: '#f08838', O: '#c05818', E: '#2a1408', K: '#5c2410' },
    grid: [
      '..K.........K...',
      '.KoK.......KoK..',
      '..KooKKKKKooK...',
      '...KooooooooK...',
      '...KoEooooEoK...',
      '...KooooooooK...',
      '....KoOOOOoK....',
      '..KoKooooooKoK..',
      '.Ko.KooooooK.oK.',
      '.....KooooK.....',
      '.....Koo.oK.....',
      '....KK....KK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  salamander: {
    pal: { r: '#e05838', R: '#a83820', Y: '#f8c848', E: '#2a1408', K: '#5c2410' },
    flip: true,
    grid: [
      '................',
      '.KK.............',
      'KrrK............',
      'KrErK...........',
      '.KrrKKKKKKKKK...',
      '.KrrrrrrrrrrrK..',
      '..KrrRRRRrrrrK..',
      '..KrrYYYYrrrK...',
      '...KrrrrrrrK....',
      '...KrK.KrK.rrK..',
      '...KK...KK..KK..',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  magmaGolem: {
    pal: { D: '#4a3830', d: '#2e2420', O: '#f08030', E: '#f8a848', K: '#1c1410' },
    grid: [
      '....KKKKKK......',
      '...KDDDDDDK.....',
      '..KDDEDDEDDK....',
      '..KDDDDDDDDK....',
      '.KKDDOddODDKK...',
      'KDDKDDDDDDKDDK..',
      'KDd.KDODDK.dDK..',
      'KDK.KDDDDK.KDK..',
      '....KDDDDK......',
      '...KDDdDDDK.....',
      '...KDD..DDK.....',
      '..KKK....KKK....',
      '................',
      '................',
      '................',
      '................',
    ],
  },

  // ================= владыки (мини-боссы) =================
  lordStorm: {
    pal: { S: '#c8d0dc', s: '#f0f4f8', B: '#3a8ae8', b: '#78c0ff', G: '#d8a030', g: '#f4d060', E: '#78d8ff', K: '#28303c' },
    grid: [
      '....gg.BB.gg....',
      '...g..BbbB..g...',
      '..g.SSBbbBSS.g..',
      '..gSSSSBBSSSSg..',
      '...SSbSSSSbSS..b',
      '...SSbESSEbSS..b',
      '....SSSSSSSS...b',
      '..SSSGGGGGGSSS.b',
      '.SSsSKBBBBKSsSSb',
      '.SSsSKBGGBKSsSSb',
      '.SS.SKBGGBKS.SSb',
      '..S.SKBBBBKS..b.',
      '....SSS..SSS..b.',
      '...GSS....SSG.b.',
      '...GG......GG...',
      '................',
    ],
  },
  lordOcean: {
    pal: { T: '#1e7a72', t: '#4ecdc4', W: '#e8f0f4', G: '#d8a840', g: '#f4d878', E: '#78d8ff', K: '#123c38' },
    grid: [
      '..g...gggg...g.g',
      '...g.gTTTTg.g.gg',
      '..ggTTttttTTgg.G',
      '...TTgttttgTT..G',
      '...TTgEttEgTT..G',
      '....TWWWWWWT...G',
      '....WWWWWWWW...G',
      '..TTTGGGGGGTTT.G',
      '.TTtTKTTTTKTtTTG',
      '.TTtTKGTTGKTtTTG',
      '.TT.TKTGGTKT.TTG',
      '..T.TKTTTTKT..G.',
      '....TTT..TTT..G.',
      '...GTT....TTG.G.',
      '...GG......GG...',
      '................',
    ],
  },
  lordNature: {
    pal: { N: '#4a9838', n: '#78c85a', D: '#7a5838', G: '#d8a030', g: '#a8e060', E: '#d8f860', S: '#8a9098', K: '#1e3c14' },
    grid: [
      '..DD..gggg..DD.S',
      '.DggD.gNNg.DggDS',
      '..DDgNNNNNNgDDSS',
      '...gNNgNNgNNg..D',
      '...gNNEggENNg..D',
      '....NNnnnnNN...D',
      '....gNNNNNNg...D',
      '..NNgGGGGGGgNN.D',
      '.NNnNKNNNNKNnNND',
      '.NNnNKGNNGKNnNND',
      '.NN.NKNGGNKN.NND',
      '..N.NKNNNNKN..D.',
      '....NNN..NNN..D.',
      '...GNN....NNG...',
      '...GG......GG...',
      '................',
    ],
  },
  lordMoon: {
    pal: { W: '#ece8f4', w: '#c8c0dc', P: '#8a5cc8', p: '#b48ae8', G: '#d8a840', g: '#f4d878', E: '#e0c8ff', K: '#241c30' },
    grid: [
      '.W...g..g...W...',
      '.WW.gPPPPg.WW.g.',
      '..WWPppppPWW.gGg',
      '..WPpWWWWpPW..G.',
      '...WPEWWEPW...G.',
      '...WWpWWpWW...G.',
      '....WWWWWW....G.',
      '..WWPGGGGPWW..G.',
      '.WWwWKPPKWwWW.G.',
      '.WWwWKPGKWwWW.G.',
      '.WW.WKGPKW.WW.G.',
      '..W.WKPPKW.W..G.',
      '....WWW..WWW..G.',
      '...GWW....WWG...',
      '...GG......GG...',
      '................',
    ],
  },
  lordFire: {
    pal: { R: '#c03028', r: '#e05848', O: '#ff9838', G: '#d8a030', g: '#f4d060', K: '#241a18', E: '#ffb066' },
    grid: [
      '..O..OOOO..O....',
      '.OO.ORRRRO.OO..O',
      '..ORRrrrrRRO...O',
      '..GRRKrrKRRG..OO',
      '...RKEREKOR...O.',
      '...GKKKKKKG...O.',
      '....RrrrrR....O.',
      '..RRGGGGGGRR..O.',
      '.RRrKKRRKKrRR.O.',
      '.RRrKRGGRKrRR.O.',
      '.RR.KRGGRK.RR.O.',
      '..R.KRRRRK.R..O.',
      '....KKK..KKK..O.',
      '...GKK....KKG...',
      '...GG......GG...',
      '................',
    ],
  },

  // ================= иконки предметов =================
  iconWeapon: {
    pal: { s: '#e8ecf2', d: '#a8b4c4', K: '#28303c', G: '#d8a030', g: '#f4d060' },
    grid: [
      '..............KK',
      '.............KsK',
      '............KssK',
      '...........KsdK.',
      '..........KsdK..',
      '.........KsdK...',
      '........KsdK....',
      '.......KsdK.....',
      '..KK..KsdK......',
      '..KgKKsdK.......',
      '...KgsdK........',
      '....KgK.........',
      '...KgGgK........',
      '..KgK.KgK.......',
      '.KK....KK.......',
      '................',
    ],
  },
  iconArmor: {
    pal: { b: '#7a90b0', d: '#54687e', s: '#c8d4e0', K: '#28303c', g: '#f4d060' },
    grid: [
      '................',
      '..KKK.....KKK...',
      '.KsssK...KsssK..',
      '.KsbKKKKKKKbsK..',
      '..KKbbbbbbbKK...',
      '...KbbdddbbK....',
      '...KbdgggdbK....',
      '...KbbdgdbbK....',
      '...KbbbdbbbK....',
      '....KbbbbbK.....',
      '....KdbbbdK.....',
      '.....KbbbK......',
      '......KKK.......',
      '................',
      '................',
      '................',
    ],
  },
  iconRing: {
    pal: { g: '#f4d060', K: '#28303c', P: '#e0b8ff', p: '#a060d8' },
    grid: [
      '.....KKKKK......',
      '....Kg...gK.....',
      '...Kg.....gK....',
      '...Kg.....gK....',
      '....Kg...gK.....',
      '.....KgggK......',
      '......KKK.......',
      '.....KKpKK......',
      '....KppppK......',
      '...KppPPppK.....',
      '...KpPPPPpK.....',
      '...KppPPppK.....',
      '....KppppK......',
      '.....KppK.......',
      '......KK........',
      '................',
    ],
  },

  // ================= финальный босс =================
  madGod: {
    pal: { K: '#1c1420', k: '#342838', R: '#e83030', r: '#ff6858', G: '#d8a030', g: '#f4d060' },
    grid: [
      '..R..g.gg.g..R..',
      '....ggGGGGgg....',
      '...GKKKKKKKKG...',
      '...KKRKKKKRKK...',
      '...KKrRKKRrKK...',
      '....KKKKKKKK....',
      '..KKKGGGGGGKKK..',
      '.KKkKKKKKKKKkKK.',
      '.KKkKRKKKKRKkKK.',
      '.KK.KKRrrRKK.KK.',
      '..K.KKKrrKKK.K..',
      '....KKKKKKKK....',
      '....KKK..KKK....',
      '...GKK....KKG...',
      '...GG......GG...',
      '................',
    ],
  },
};

function makeSprite(def) {
  const c = document.createElement('canvas');
  c.width = 16; c.height = 16;
  const g = c.getContext('2d');
  def.grid.forEach((row, y) => {
    for (let x = 0; x < Math.min(row.length, 16); x++) {
      const col = def.pal[row[x]];
      if (!col) continue;
      g.fillStyle = col;
      g.fillRect(x, y, 1, 1);
    }
  });
  return c;
}
const sprites = {};
for (const k in SPRITES) sprites[k] = makeSprite(SPRITES[k]);

// превью спрайтов классов в карточках меню
document.querySelectorAll('.card-sprite').forEach(c => {
  const s = sprites[c.dataset.cls];
  if (!s) return;
  const g = c.getContext('2d');
  g.imageSmoothingEnabled = false;
  g.drawImage(s, 0, 0, c.width, c.height);
});
